### ISSUE TITLE
CodeChat has failed to install

### ISSUE THREAD

**Issue by andreikop** [andreikop/enki#433]
I've tried to switch to setuptools, and got this error:
```
Searching for CodeChat
Reading https://pypi.python.org/simple/CodeChat/
Best match: CodeChat 1.4.1
Downloading https://pypi.python.org/packages/6a/1d/ff8b467e1ed1a5c5b3d28da04e9853595599ee4203d842dd88d9c459f905/CodeChat-1.4.1.tar.gz#md5=824e5f91f231f50493b59ab5784e2cb7
Processing CodeChat-1.4.1.tar.gz
Writing /tmp/easy_install-q6kqkvjy/CodeChat-1.4.1/setup.cfg
Running CodeChat-1.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-q6kqkvjy/CodeChat-1.4.1/egg-dist-tmp-q02bi_eq
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-q6kqkvjy/CodeChat-1.4.1/setup.py", line 91, in <module>
    ]
ImportError: No module named 'ez_setup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./setup.py", line 141, in <module>
    'flake8',
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-q6kqkvjy/CodeChat-1.4.1/setup.py", line 91, in <module>
    ]
ImportError: No module named 'ez_setup'
```

**Comment by rapgro** [comment]
Did you try? $ $ pip install ez_setup && pip install ez_setup

They write something strange may b0rked in your python installation.
Found this for you: https://stackoverflow.com/questions/32027994/no-module-named-ez-setup/36042870#36042870

**Comment by andreikop** [comment]
@rapgro , I can install ez_setup manually.
But I'd like `./setup.py install` works out of the box

@bjones1, I see that CodeChat setup.py imports. ez_setup, which is not installed on my machine.
The problem is described [here](https://pypi.python.org/pypi/ez_setup)

**Comment by bjones1** [comment]
I *think* that simply importing setuptools instead of distutils would fix this. I'm swamped right now but will take a look as soon as I can!

**Comment by andreikop** [comment]
CodeChat version, which is hosted on PyPI, imports ez_setup.
Try to remove this import

**Comment by bjones1** [comment]
CodeChat is updated, this should be fixed now.

**Comment by andreikop** [comment]
Thanks, works fine now.
I've switched Enki to setuptools
