### ISSUE TITLE
I insert 🔇 into a html page and Enki shows a backtrace

### ISSUE THREAD

**Issue by vi** [andreikop/enki#438]
`U+1F507 SPEAKER WITH CANCELLATION STROKE`

```
Traceback (most recent call last):
  File "/home/vi/src/git/qutepart/qutepart/__init__.py", line 1278, in _updateExtraSelections
    cursorColumnIndex)
  File "/home/vi/src/git/qutepart/qutepart/brackethlighter.py", line 142, in extraSelections
    blockText[columnIndex - 1] in self._ALL_BRACKETS and \
IndexError: string index out of range
```

```
Traceback (most recent call last):
  File "/home/vi/src/git/qutepart/qutepart/__init__.py", line 844, in _dropUserExtraSelections
    self.setExtraSelections([])
  File "/home/vi/src/git/qutepart/qutepart/__init__.py", line 863, in setExtraSelections
    self._updateExtraSelections()
  File "/home/vi/src/git/qutepart/qutepart/__init__.py", line 1278, in _updateExtraSelections
    cursorColumnIndex)
  File "/home/vi/src/git/qutepart/qutepart/brackethlighter.py", line 142, in extraSelections
    blockText[columnIndex - 1] in self._ALL_BRACKETS and \
IndexError: string index out of range
```

Also the symbol is visible as two question mark replacement characters.

Enki + Unicode  = 💔

**Comment by vi** [comment]
The character shows up if I type a digit after it.
