### ISSUE TITLE
test_base.TestWaitForSignal fails in Fedora 29

### ISSUE THREAD

**Issue by rapgro** [andreikop/enki#456]
Fedora 29: For all of the test_X calls with X in between of 1 to 10:

```
ERROR: test_X (test_base.TestWaitForSignal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/enki-18.08.0/tests/test_base.py", line 114, in test_9
    ts.testSignalArgs, 100, (2,)))
  File "/builddir/build/BUILD/enki-18.08.0/tests/base.py", line 464, in waitForSignal
    sip.delete(timer)
TypeError: delete() argument 1 must be sip.simplewrapper, not QTimer
```

Please let me know if any other information required to reproduce. This issue seems similiar to https://github.com/andreikop/enki/commit/0404b84f19d7cc96a886615cd3f73cf48998ef88

**Comment by rapgro** [comment]
Thanks for your feedback. I use ugly hackery in my spec file to disable those failing tests.
