### ISSUE TITLE
Choosing Vim mode tutorial hangs Enki

### ISSUE THREAD

**Issue by abitrolly** [andreikop/enki#460]
I am using master. When I chosen `Vim mode tutorial` from the help menu it worked okay, but then I right clicked and selected `Show source` in preview area to see if I can change font to monospace. It is when it hung for the first time and now it hangs just when `Vim mode tutorial` is selected.

**Comment by andreikop** [comment]
Does it hang if you open REAME.md and show Preview?

**Comment by andreikop** [comment]
And watch the source

**Comment by abitrolly** [comment]
Hangs with `README.md` too.

> And watch the source

How to do this?

**Comment by andreikop** [comment]
Which PyQt5 do you use? From repo or from pip?
Could you try another variant?

What is your PyQt5 version?

**Comment by andreikop** [comment]
Hmm, it seems like preview hangs for you. I'm surprised. 

I have 3 suspects:
* QtWebEngine
* Preview sync code
* Markdown

Could you please open .html file in Enki and see preview? Does Enki hang?

**Comment by bjones1** [comment]
This is just a wild guess, but sometimes regex works poorly in the preview sync. Can you `pip3 uninstall regex` and see if that helps?

**Comment by andreikop** [comment]
@abitrolly ?

**Comment by abitrolly** [comment]
Enki hangs with .html preview.

`dnf uninstall python3-regex` fixed all hangs. :open_mouth:

**Comment by abitrolly** [comment]
https://github.com/andreikop/enki/commit/33896d770c58ce5bc3e3215ebbf7375e4e284a12

**Comment by dglent** [comment]
I have this error after removing the package codechat:
``` python
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/enki/plugins/preview/__init__.py", line 467, in _onDocumentChanged
    self._createDock()
  File "/usr/lib/python3.8/site-packages/enki/plugins/preview/__init__.py", line 497, in _createDock
    self._dock = PreviewDock()
  File "/usr/lib/python3.8/site-packages/enki/plugins/preview/preview.py", line 482, in __init__
    self.previewSync = PreviewSync(self)
  File "/usr/lib/python3.8/site-packages/enki/plugins/preview/preview_sync.py", line 168, in __init__
    if not findApproxTextInTarget:
NameError: name 'findApproxTextInTarget' is not defined
```
It needs to define findApproxTextInTarget in any case:
 https://github.com/andreikop/enki/blob/33896d770c58ce5bc3e3215ebbf7375e4e284a12/enki/plugins/preview/preview_sync.py#L38

i did this:
``` python
try:
    pass
    # Approx matching is disabled because of issue #460
    # from .approx_match import findApproxTextInTarget
except ImportError as e:
    findApproxTextInTarget = None
finally:
    findApproxTextInTarget = None
```

**Comment by andreikop** [comment]
PR is welcome!

**Comment by dglent** [comment]
> PR is welcome!

No need, i was not updated :)
https://github.com/andreikop/enki/commit/aafee43a1d4c9d8f4e15055b1e13a20578d990ce
