### ISSUE TITLE
Errors on ArchLinux, related to qutepart

### ISSUE THREAD

**Issue by Ododo** [andreikop/enki#462]
Hello, 

i encounter this issue using the AUR git package:
(prevents me to open some files, to have syntax coloration, python console etc)

CRITICAL:root:Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/enki/plugins/session.py", line 76, in _onRestoreSession
    core.workspace().openFile(filePath)
  File "/usr/lib/python3.7/site-packages/enki/core/workspace.py", line 590, in openFile
    document = self._openSingleFile(filePath)
  File "/usr/lib/python3.7/site-packages/enki/core/workspace.py", line 571, in _openSingleFile
    document = Document(self, filePath)
  File "/usr/lib/python3.7/site-packages/enki/core/document.py", line 206, in __init__
    self._tryDetectSyntax()
  File "/usr/lib/python3.7/site-packages/enki/core/document.py", line 220, in _tryDetectSyntax
    firstLine=self.qutepart.lines[0])
  File "/usr/lib/python3.7/site-packages/qutepart/__init__.py", line 772, in detectSyntax
    firstLine=firstLine)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/__init__.py", line 250, in getSyntax
    syntax = self._getSyntaxBySourceFileName(baseName, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/__init__.py", line 195, in _getSyntaxBySourceFileName
    return self._getSyntaxByXmlFileName(xmlFileName, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/__init__.py", line 180, in _getSyntaxByXmlFileName
    qutepart.syntax.loader.loadSyntax(syntax, xmlFilePath, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/loader.py", line 595, in loadSyntax
    _loadContexts(highlightingElement, syntax.parser, attributeToFormatMap, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/loader.py", line 389, in _loadContexts
    _loadContext(context, xmlElement, attributeToFormatMap, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/loader.py", line 427, in _loadContext
    rules = _loadChildRules(context, xmlElement, attributeToFormatMap, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/loader.py", line 176, in _loadChildRules
    rule = _ruleClassDict[ruleElement.tag](context, ruleElement, attributeToFormatMap, formatConverterFunction)
  File "/usr/lib/python3.7/site-packages/qutepart/syntax/loader.py", line 316, in _loadRegExpr
    string, insensitive, minimal, wordStart, lineStart)
TypeError: function takes at most 5 arguments (6 given)

**Comment by andreikop** [comment]
I really don't understand how did this happen.
loader.py:316 calls RegExp class constructor.
There are 2 implementations: [1](https://github.com/andreikop/qutepart/blob/master/qutepart/syntax/parser.py#L384), [2](https://github.com/andreikop/qutepart/blob/master/qutepart/syntax/parser.py#L384)

And both have exactly 6 parameters.
Could you clone [qutepart](https://github.com/andreikop/qutepart) and try to run it from the sources?
```
cd qutepart
./editor.py editor.py
```
This lines will execute this code and run editor with the highlighting

**Comment by Ododo** [comment]
The editor works when cloning qutepart,

maybe it is related to the way my system is building cParser extension

**Comment by Ododo** [comment]
I still have the error, and "with binary parser" is written
