### ISSUE TITLE
Crash on boot after first save

### ISSUE THREAD

**Issue by fahrradflucht** [andreikop/enki#469]
I opened enki on a fresh install of Fedora r LXqt (rawhide). I wrote a couple of lines of python, saved and got a crash message (enki still worked after acknowledging the crash).

Now every time I start enki I get the same crash message (always recoverable).

About Enki:
Version 20.03.1
Qutepart 3.3.1
Qt 5.14.2

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/enki/plugins/session.py", line 76, in _onRestoreSession
    core.workspace().openFile(filePath)
  File "/usr/lib/python3.9/site-packages/enki/core/workspace.py", line 590, in openFile
    document = self._openSingleFile(filePath)
  File "/usr/lib/python3.9/site-packages/enki/core/workspace.py", line 571, in _openSingleFile
    document = Document(self, filePath)
  File "/usr/lib/python3.9/site-packages/enki/core/document.py", line 206, in __init__
    self._tryDetectSyntax()
  File "/usr/lib/python3.9/site-packages/enki/core/document.py", line 219, in _tryDetectSyntax
    self.qutepart.detectSyntax(sourceFilePath=self.filePath(),
  File "/usr/lib64/python3.9/site-packages/qutepart/__init__.py", line 788, in detectSyntax
    syntax = self._globalSyntaxManager.getSyntax(xmlFileName=xmlFileName,
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/__init__.py", line 250, in getSyntax
    syntax = self._getSyntaxBySourceFileName(baseName)
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/__init__.py", line 195, in _getSyntaxBySourceFileName
    return self._getSyntaxByXmlFileName(xmlFileName)
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/__init__.py", line 180, in _getSyntaxByXmlFileName
    qutepart.syntax.loader.loadSyntax(syntax, xmlFilePath)
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/loader.py", line 629, in loadSyntax
    _loadContexts(highlightingElement, syntax.parser, attributeToFormatMap)
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/loader.py", line 421, in _loadContexts
    _loadContext(context, xmlElement, attributeToFormatMap)
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/loader.py", line 461, in _loadContext
    rules = _loadChildRules(context, xmlElement, attributeToFormatMap)
  File "/usr/lib64/python3.9/site-packages/qutepart/syntax/loader.py", line 205, in _loadChildRules
    for ruleElement in xmlElement.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by andreikop** [comment]
Hi
Sorry for a long delay. Will try to check this soon

**Comment by andreikop** [comment]
@fahrradflucht , could you please show your session?
```
cat  ~/.config/enki/session.json
```
Wipe private data if necessary. I'm just interested which file type is opened. It seems like the editor fails to parse syntax definition XML file. I'm surprised.
