### ISSUE TITLE
Enki crashes on opening -persists event after uninstall and reinstall in Fedora LXQT 

### ISSUE THREAD

**Issue by mitradranirban** [andreikop/enki#479]
There is an Oops, Internal exeption witdow appearing on opening any file with following information 
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/qutepart/__init__.py", line 1287, in paintEvent
    self._drawIndentMarkersAndEdge(event.rect())
  File "/usr/lib64/python3.10/site-packages/qutepart/__init__.py", line 1279, in _drawIndentMarkersAndEdge
    drawWhiteSpace(block, column, text[column])
  File "/usr/lib64/python3.10/site-packages/qutepart/__init__.py", line 1198, in drawWhiteSpace
    painter.drawRect(QRect(xPos, middleHeight, 2, 2))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'

**Comment by mitradranirban** [comment]
The window hangs and can not be closed except kill from terminal 
Please see screenshot Enki Version 21.11.0 Relaese2.fc36 
![enki-screenshot](https://user-images.githubusercontent.com/67600799/170316790-08b49075-c080-43a8-ba65-05bad7034482.png)

**Comment by nixuser58** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=2066026

**Comment by andreikop** [comment]
Fixed in 22.08
I hope  @rapgro will release it soon
