### ISSUE TITLE
BUG: `AttributeError` during Markdown Preview

### ISSUE THREAD

**Issue by sohang3112** [andreikop/enki#484]
When I opened a Markdown document in Enki, it gave this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/enki/lib/future.py", line 503, in onDoneSignal
    future._g(future)
  File "/usr/lib/python3.12/site-packages/enki/plugins/preview/preview.py", line 997, in _setHtmlFuture
    filePath, htmlText, errString, baseUrl = future.result
                                             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/enki/lib/future.py", line 472, in result
    raise value.with_traceback(traceback)
  File "/usr/lib/python3.12/site-packages/enki/lib/future.py", line 424, in _invoke
    self._result = self._f(*self._args, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/enki/plugins/preview/preview.py", line 920, in getHtml
    return filePath, _convertMarkdown(text), None, QUrl()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/enki/plugins/preview/preview.py", line 107, in _convertMarkdown
    if markdown.version_info[0] > 2 or \
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown' has no attribute 'version_info'. Did you mean: '__version_info__'?
```
Here, the fix for this seems obvious (it's mentioned in the error message itself) - if `markdown.version_info` fails, then try `markdown.__version_info__`.

## Environment Info
- Python 3.12
- Version of `markdown` python library: 3.5.2
- Version of Enki: 22.8.0

**Comment by themanyone** [comment]
Addressed in #488
